from .tbg_nodes import NODE_CLASS_MAPPINGS as TBG_NODES_MAP, NODE_DISPLAY_NAME_MAPPINGS as TBG_NODES_DISPLAY
from .TBG_sampler_split_aware import NODE_CLASS_MAPPINGS as SAMPLER_MAP, NODE_DISPLAY_NAME_MAPPINGS as SAMPLER_DISPLAY

# Merge both into single dicts
NODE_CLASS_MAPPINGS = {**TBG_NODES_MAP, **SAMPLER_MAP}
NODE_DISPLAY_NAME_MAPPINGS = {**TBG_NODES_DISPLAY, **SAMPLER_DISPLAY}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
